### ISSUE TITLE
Baumi's Idea "Radiant Jungle"

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/overmemed#3]
Kind of a play on the hero from defintely not dota "Dire Safelane", but where that is a tower, this will be a neutral creep that can spawn creeps.

Hero model: A ranged neutral creep model
Ability1: "spawn easy camp"
Ability2: "spawn medium camp"
Ability3: "spawn hard camp"
Ability4: "spawn ancient camp"

ancient one is the ult
each level up spawns 1 additional unit
each spell is a 15s channel with 60 seconds cooldown
oh no
each level up spawns 1 additional camp
so level 3 "spawn hard camp"
spawns 3 random hard camps

**Comment by Yahnich** [comment]
#4
